### ISSUE TITLE
Missing objects ZDAQO_USER and ZCL_AQO_HELPER

### ISSUE THREAD

**Issue by christianguenter2** [bizhuka/aqo_ui5#1]
Seems that data element ZDAQO_USER and class ZCL_AQO_HELPER are missing in the repo. At least I get these errors while importing the repo into NW 752 SP04 dev edition.
![image](https://user-images.githubusercontent.com/17437789/111119430-6b68f400-856a-11eb-914c-dc5ea904b109.png)

![image](https://user-images.githubusercontent.com/17437789/111119445-6efc7b00-856a-11eb-8482-97cf7e020ad4.png)

**Comment by bizhuka** [comment]
Hello
It seems to me that the main packages are not installed yet
https://github.com/bizhuka/aqo
https://github.com/bizhuka/eui   (ui libs)

just import & activate twice (regardless errors)
![image](https://user-images.githubusercontent.com/36256417/111150921-ebb64600-85b8-11eb-9c05-76b8a28e838c.png)

there are cyclic reference from data element & search help (probably I should attach SH dynamically)
![image](https://user-images.githubusercontent.com/36256417/111151013-0f798c00-85b9-11eb-833a-c23226a7d5e5.png)

if you have any errors or questions during installation feel free & write to me
I will try to make installation process easier

**Comment by christianguenter2** [comment]
yeah aqo was missing. Thanks for your quick reply. Closing.
